server:
  port: 8888
  
    
spring:
  application:
    name: SHOP-EAZY-CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mapoulo/shopEazyCloudConfig1
          clone-on-start: true  
          default-label: master
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0       
      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest         
          
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'  
                        