server:
  port: 9191

logging:
  level:
    '[org.springframework.cloud.gateway.route.RouteLocator]': INFO
    root: INFO
    '[org.springframework.cloud.gateway]': TRACE
      
spring:
  application:
    name: ONLINESHOPPING-GATEWAY-SERVICE
  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: product-service
        uri:
          lb://product-service
        predicates:
        - Path=/api/product/
      - id: order-service
        uri:
          lb://order-service
        predicates:
        - Path=/api/order/  
      - id: ONLINESHOPPING-GATEWAY-SERVICE
        uri:
          http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/  
      - id: ONLINESHOPPING-GATEWAY-SERVICE-static
        uri:
          http://localhost:8761
        predicates:
        - Path=/eureka/**
         
       

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}        